name: Android CI

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # JAVA_HOME leaks after this step
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Gradle command
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        script: publishReleasePublicationToMavenRepository
        args: build -PsonatypeUsername=${{secrets.SONATYPE_USERNAME}} -PsonatypePassword=${{secrets.SONATYPE_PASSWORD}}
